-- NexFlow CRM: Create Expenses Table
-- Module: Expenses
-- Tenant Isolation: organization_id with CASCADE foreign key

CREATE TABLE IF NOT EXISTS `expenses` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT(10) UNSIGNED NOT NULL,
  `reference_number` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `expense_date` DATE NOT NULL,
  `merchant` VARCHAR(255) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `currency` VARCHAR(30) NOT NULL,
  `tax_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `billing_type` ENUM('Billable', 'Non-Billable') NOT NULL,
  `invoice_status` ENUM('Not Invoiced', 'Invoiced') NOT NULL,
  `invoice_reference` VARCHAR(100) DEFAULT NULL,
  `invoiced_at` DATETIME DEFAULT NULL,
  `invoiced_by` INT(10) UNSIGNED DEFAULT NULL,
  `reimbursement_status` ENUM('N/A', 'Pending', 'Reimbursed') NOT NULL,
  `reimbursed_at` DATETIME DEFAULT NULL,
  `company_id` INT(10) UNSIGNED DEFAULT NULL,
  `project_id` INT(10) UNSIGNED DEFAULT NULL,
  `payment_method` VARCHAR(100) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `receipt_filename` VARCHAR(255) DEFAULT NULL,
  `receipt_path` VARCHAR(500) DEFAULT NULL,
  `receipt_mime` VARCHAR(100) DEFAULT NULL,
  `receipt_size` INT(11) DEFAULT NULL,
  `owner_id` INT(10) UNSIGNED DEFAULT NULL,
  `created_by` INT(10) UNSIGNED DEFAULT NULL,
  `updated_by` INT(10) UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_expenses_org_ref` (`organization_id`, `reference_number`),
  KEY `idx_expenses_org_date` (`organization_id`, `expense_date`),
  KEY `idx_expenses_org_category` (`organization_id`, `category`),
  KEY `idx_expenses_org_billing` (`organization_id`, `billing_type`),
  KEY `idx_expenses_org_invoice` (`organization_id`, `invoice_status`),
  KEY `idx_expenses_org_reimburse` (`organization_id`, `reimbursement_status`),
  KEY `idx_expenses_company` (`company_id`),
  KEY `idx_expenses_project` (`project_id`),
  KEY `idx_expenses_owner` (`owner_id`),
  CONSTRAINT `fk_expenses_org` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_expenses_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_expenses_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_expenses_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_expenses_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_expenses_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_expenses_invoiced_by` FOREIGN KEY (`invoiced_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
